---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongodb-secret
  namespace: default
spec:
  encryptedData:
    uri: AgCL0MC98IVDrc1L72YRlZU6uifbOXUPuzbl/vHPYA9voZDgiOmSkNwhHUxYXZx32KTtQVVM/AnYR7JDHtC6OUxec4KzMJi2+bRUFLlbH40GaoucGVO4scZkdNVajyyt/1i1hj0EYTZxTWZnTIMmKjd8ZyBLSZNjmXyYC3oXqeEZfiSDKIHAKUoEzcnK70lIbCQaIo+qqlbX7QK2KYhBsilet9SZEp0iETEympbyvlpKPRFhsAnxOj8wjzWG4XQoc1dmq0Ukzwzr3cgAdIEy16bBXVNd/PezCQDd6Iy04RL2M2hG/lkFYntDHEiBB7mBA0sKjL3FhoAN6/nJtHGKz5c4rHhIVbOphgoZtIsO8XrCT1J7zefgXTvDJq/nDF1qLEpHwLmC+sBwiXthJbYThV+sjozcCAH3wfH26hfc8kXvJQAv/3Cme1GsJONxrzhuzsv5kZzcrPnhkN8297WpMqZV+wQuUDD4RWtCTy4iWV0lTz5bRZTyuy/INdD/I6wwA5K99Yj9uQ7uOWEY6bTLTKSchuL0aOi1V8Aw35joLxqbctQ3JDoADmPHWQRIlZh7AkuF9UNqEnvqPrAuH2pTKFaWZstkAjpl4tExIQyTqrxtZm782upaHRzuwSkdmlZsMobQsUqhfvdaSnyXuamv5bAD2lyyl7W3Yjnm8AbaV7Ghfn4h463OKVxjqpy8mN+fakXICLVk2mJx3ih7ynaovvnVUvucMMvVrUO5e4tzQZB1sP3Xa5UiugKBrhFmoe66ru7N0f1KATWV38GSl1n95B0frRXJra9GCkFtILO6gnD5zrn4XM2hzi+adQQq8sUjRX5DltVWe38XWdxDOjhPiRJo
  template:
    metadata:
      creationTimestamp: null
      name: mongodb-secret
      namespace: default
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rabbitmq-secret
  namespace: default
spec:
  encryptedData:
    tls: AgAsiEBbu7Lt0Mdc3EcSHK5iSr9MflsX3Sy0y62FwozPU3xOJrZYVE2fqAG/BH3CeHFYV6sJNPYQtPT+WXrY77q5E53lz79A7aHUOpSvRG0VuyXS7tmIbglkxwR/tPRKCZMQdGp14yjBHP2iffego39VlSH1tImyVg2fvzQ8IBz2rd5uS4QLfgAZR2g/LX4Wve0WwTcKyfr2oUsrmxtSc58OnMjuzQkSc0aZR3/OmGX2KQBMSi2eB8LtClOQ5bxul9h3Ydfp46XQiSKtd+A6vl8SYHxE8XASK+cszw2UjguCJfzquAVCgmMMWPi5OIhI06l8oVaG7TxMDPJxFzJT12XC1BzSsB5ikF7+XrV8icjr0Zdq7kPVEqDB8OvsoPeDdReIUl7uFlnYF8SiIdKC/D8IZAe80H/bTJ6C53U6l1u1VoW2GndLEcHvGu5Uvp4Ocr7V3UU+8i8do/NMG+fgjJgYL4LAihVLmNljNoRUfcYK4BWux3hrr9NPdTkxhn5qLRxaxapo7jNzAoMm7qEh3TOMqYOe4RjDVeK6fK69ruF71JDo0i/8L/zXgMySDbC1i+jH5RJuxrzMLNL12LW1GQHb/t++PiJOkNOVfEukh83aQ6SAyJxf50f8UAWdhaG+peJcrD1LKCaFD1+9yuANjFmB9QjgV3b3/oezrNXxDXF3iYlKLpoEfzHLsQA763K6uVFdRnFfX6Y=
    uri: AgCdeelrLVU/thTJ7HL5fBpU7Mi2n5gaNCUAwMR/iBR74Xx4Awmp1PIKY6Xr0cd1qmytSv3wiblhYiZxxsh1lWBz7658DwQiEb6sXtS3JRcdBooaEkRxYVYhrpDru/mb3N1BTuaUkNnZAMfYeY4N5nZxudPY5BN1gsD0IqbXqTf+0hWTpNatkube3FFR5g8zbB+oPI+cqAoHIsUzAAJVj+ON3g6dsiXjyriiuMjC142K8Qky/UgSPao6oHdFlSbXFrWlTHcmi87oXTYHf3dDivj/etEcshjVURfX+25WSI5K2Qx6xgnqutHRNJg1Bg9nAb5qS4N/87GHcxuO1HnJ+SYxr77MJsPftR2Zp+w7UCvGX2sBsUIa1eNJ8Rw/LO3x23clUetql6Frv7yzdMunFNackAfm46ar39ZowMVJ3ce9p0xdFCrCMYTTpjdjwTxGxBlSp1LaqPes3K5iZHdvn0r6EC5W8NnSW3Qt6SVsWkJPxVaVRh6IJ5aP1ES2TE76FlZahVouRYqoKEHqsw7uvWfpk2nPbmqhE/gMOo4uq3v/9oSSCYWOYEEz37uRgT1VYswOyTXHIXyrKh5Fhtg9UPmMWEA4LB4yQndf8uDLJJHAHd/JBlDDlN9rRZnCUtMTlDljJSHLmb7ELtlpyDI46n8plaGv98PZnW6h073w3rvmiLA4nZY+FXpDD0blsJQUu893JMedXN9knKGBhncC44spoovv11tp3HwqslTGQR3LKYkiOVws0LeKMnN498IfO54Y048FgpzZzYycNUxL4LDRpKlEIilPMJz6vOIo9LLxMEMI6T327MbvmK/c8JvZfeOxf4aSPbIFpDdoBmggCb7cIQ==
  template:
    metadata:
      creationTimestamp: null
      name: rabbitmq-secret
      namespace: default
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-secret
  namespace: default
spec:
  encryptedData:
    access-key-id: AgAkmTREfDKiVMmQVNYi9GKqS3mpMLzLxLkFFvC5webcKP6XJTByrQ6b3Dn4OjMTcNoXG0RU0Eb3AhOdxCU1+2T1DgkwMF6+xKdZUKmWQnlif6Yu8VAA2pNJsqNZ0VIOAu4LUlYkVDqiQpyuz0GdDB8SUu2c0s5OjwhcD4gLCLJ4Ptgat5Hy+3FDLi6WiD4PMj5a9GC0TOrKHqPGIAvY9nca/xs3WvYL3ke3rU43XzhxzsmisO4A0jD4tBBFc3J5TbZkjK4MnxA6Sbnxz6PR8xEl1TXl3Ng2QT/q/lRADDQdlU49vJQ4W6LlCB5vdvnUMHVUOxCqHIKD0u9yZboUkqbiwEN25Kt+Oma2MVAKUIBWONV/MXciLbUoA9R48imZvMotLlVrWXYRtU1Qvx9LBp+mBI00x48cDzTWzMrFGd4N6dvWqggB+4ij0LV3nz4wNKkvfgkfF2Jjg5LnNopoJD2a5bqpezoBS0iMoa5vrCKxakp9876xradW39bflxOK2NXzuhITNgeNmTtLXEZmjC2vzOkGiPlal0HHjr34WYCrORllc+r6Axkg9V5tVNeQfh5uJnXo15FuEVpn4hbK8QBvt2G2sQQFE87R8LEtG7bnHoZsU+qEtjxcC3QilgEBf7GrDmKOppu52xiGgxJzNAEjp2rbfANGv6ZpPBgkroqLIYm75B5JzKQagjU/eQOS6cx68xtwee71lMxko3umSPxilcN2OQ==
    secret-access-key: AgADNNKVBHdClQ0Y0kU0TA9V7LpwROgCt2AmstysYVmnqa8S3AYTVf+GZcwUTUSs9e5mamoJWB5MoI+CebqenNnnRV4WDCfSJ+akpPEvSs3uDCDUdXrw3C9wEnYlm1HiBCLW7dmsjiwD8tTL70xYGwttJfjGCRxsgoY7fuHN8gvZ3EAshleuf6g3DHqwdYlAUi2IRyQ/v0BYvVz4VcvrY+E+JhTPBwHhK6hTz94X2tXyGLfV9qQcwJ/xrKiVaHNAyWotWJ6oELA2/15mEQ+52z6dcJGQX8CGOOtuKIhExVk478tawwdySkzZdtjlXmQAnWsrlnsVWEzth9mtuk47Yg9GoOolOi+STw7MuDDFGsQQ4Tu2ykf6XO9HDHczf6XEtsZ/R3V2VzjmENX8H/dZXVEbqF5/owcjBJrul55+WX/NsCWuQYdSEfZ0yx91u7UA3hnw+QYUQ0+7C5+XwQPtKaXhgjmgWoUe41VHg2F0uWjna7yvNwQtF7L+Fw9LQv7Vxue61pCwY2QlhCAmXUsCIyXhbMZddghbpktVxhaCFWfsAq3nAAnkpEwT4v3x+NTPnDWRo8O+egs3fqgMqr6yb6A3ta1f3bSJiuW/iULMOK4+CUwkAOX0DWQfyNvGW1oDr09SxljahG7rTErmkfbyWTJ1t/UIl8brn94GfL9n+Ma5g4W28/9N1+rAJihhe/MNmtxouLkz6RtO0OYnExEEqKH/Xs2bAi4saru5dF7yvCiNURr52bUgdPro
  template:
    metadata:
      creationTimestamp: null
      name: aws-secret
      namespace: default
    type: Opaque
